create table sys_menu
(
    menu_id     bigint auto_increment comment '菜单ID'
        primary key,
    menu_name   varchar(50)              not null comment '菜单名称',
    parent_id   bigint       default 0   null comment '父菜单ID',
    order_num   int          default 0   null comment '显示顺序',
    path        varchar(200) default ''  null comment '路由地址',
    component   varchar(255)             null comment '组件路径',
    query       varchar(255)             null comment '路由参数',
    route_name  varchar(50)  default ''  null comment '路由名称',
    is_frame    int          default 1   null comment '是否为外链（0是 1否）',
    is_cache    int          default 0   null comment '是否缓存（0缓存 1不缓存）',
    menu_type   char         default ''  null comment '菜单类型（M目录 C菜单 F按钮）',
    visible     char         default '0' null comment '菜单状态（0显示 1隐藏）',
    status      char         default '0' null comment '菜单状态（0正常 1停用）',
    perms       varchar(100)             null comment '权限标识',
    icon        varchar(100) default '#' null comment '菜单图标',
    create_by   varchar(64)  default ''  null comment '创建者',
    create_time datetime                 null comment '创建时间',
    update_by   varchar(64)  default ''  null comment '更新者',
    update_time datetime                 null comment '更新时间',
    remark      varchar(500) default ''  null comment '备注'
)
    comment '菜单权限表' collate = utf8mb4_general_ci
                         row_format = DYNAMIC;

INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1, '系统管理', 0, 996, 'system', null, '', '', 1, 0, 'M', '0', '0', '', 'system', 'admin', '2025-10-13 15:33:36', 'admin', '2025-11-08 11:52:48', '系统管理目录');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2, '系统监控', 0, 997, 'monitor', null, '', '', 1, 0, 'M', '0', '0', '', 'monitor', 'admin', '2025-10-13 15:33:36', 'admin', '2025-11-08 11:52:57', '系统监控目录');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (3, '系统工具', 0, 995, 'tool', null, '', '', 1, 0, 'M', '0', '0', '', 'tool', 'admin', '2025-10-13 15:33:36', 'admin', '2025-11-08 12:46:33', '系统工具目录');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (4, '前台', 0, 999, 'portal', null, '', '', 1, 0, 'M', '0', '0', '', 'guide', 'admin', '2025-10-13 15:33:36', 'admin', '2025-11-08 11:16:39', '若依官网地址');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (100, '用户管理', 1, 1, 'user', 'system/user/index', '', '', 1, 0, 'C', '0', '0', 'system:user:list', 'user', 'admin', '2025-10-13 15:33:36', '', null, '用户管理菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (101, '角色管理', 1, 2, 'role', 'system/role/index', '', '', 1, 0, 'C', '0', '0', 'system:role:list', 'peoples', 'admin', '2025-10-13 15:33:36', '', null, '角色管理菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (102, '菜单管理', 1, 3, 'menu', 'system/menu/index', '', '', 1, 0, 'C', '0', '0', 'system:menu:list', 'tree-table', 'admin', '2025-10-13 15:33:36', '', null, '菜单管理菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (103, '部门管理', 1, 4, 'dept', 'system/dept/index', '', '', 1, 0, 'C', '0', '0', 'system:dept:list', 'tree', 'admin', '2025-10-13 15:33:36', '', null, '部门管理菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (104, '岗位管理', 1, 5, 'post', 'system/post/index', '', '', 1, 0, 'C', '0', '0', 'system:post:list', 'post', 'admin', '2025-10-13 15:33:36', '', null, '岗位管理菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (105, '字典管理', 1, 6, 'dict', 'system/dict/index', '', '', 1, 0, 'C', '0', '0', 'system:dict:list', 'dict', 'admin', '2025-10-13 15:33:36', '', null, '字典管理菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (106, '参数设置', 1, 7, 'config', 'system/config/index', '', '', 1, 0, 'C', '0', '0', 'system:config:list', 'edit', 'admin', '2025-10-13 15:33:36', '', null, '参数设置菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (107, '通知公告', 1, 8, 'notice', 'system/notice/index', '', '', 1, 0, 'C', '0', '0', 'system:notice:list', 'message', 'admin', '2025-10-13 15:33:36', '', null, '通知公告菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (108, '日志管理', 1, 9, 'log', '', '', '', 1, 0, 'M', '0', '0', '', 'log', 'admin', '2025-10-13 15:33:36', '', null, '日志管理菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (109, '在线用户', 2, 1, 'online', 'monitor/online/index', '', '', 1, 0, 'C', '0', '0', 'monitor:online:list', 'online', 'admin', '2025-10-13 15:33:36', '', null, '在线用户菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (110, '定时任务', 2, 2, 'job', 'monitor/job/index', '', '', 1, 0, 'C', '0', '0', 'monitor:job:list', 'job', 'admin', '2025-10-13 15:33:36', '', null, '定时任务菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (111, '数据监控', 2, 3, 'druid', 'monitor/druid/index', '', '', 1, 0, 'C', '0', '0', 'monitor:druid:list', 'druid', 'admin', '2025-10-13 15:33:36', '', null, '数据监控菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (112, '服务监控', 2, 4, 'server', 'monitor/server/index', '', '', 1, 0, 'C', '0', '0', 'monitor:server:list', 'server', 'admin', '2025-10-13 15:33:36', '', null, '服务监控菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (113, '缓存监控', 2, 5, 'cache', 'monitor/cache/index', '', '', 1, 0, 'C', '0', '0', 'monitor:cache:list', 'redis', 'admin', '2025-10-13 15:33:36', '', null, '缓存监控菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (114, '缓存列表', 2, 6, 'cacheList', 'monitor/cache/list', '', '', 1, 0, 'C', '0', '0', 'monitor:cache:list', 'redis-list', 'admin', '2025-10-13 15:33:36', '', null, '缓存列表菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (115, '表单构建', 3, 1, 'build', 'tool/build/index', '', '', 1, 0, 'C', '0', '0', 'tool:build:list', 'build', 'admin', '2025-10-13 15:33:36', '', null, '表单构建菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (116, '代码生成', 3, 2, 'gen', 'tool/gen/index', '', '', 1, 0, 'C', '0', '0', 'tool:gen:list', 'code', 'admin', '2025-10-13 15:33:36', '', null, '代码生成菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (117, '系统接口', 3, 3, 'swagger', 'tool/swagger/index', '', '', 1, 0, 'C', '0', '0', 'tool:swagger:list', 'swagger', 'admin', '2025-10-13 15:33:36', '', null, '系统接口菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (500, '操作日志', 108, 1, 'operlog', 'monitor/operlog/index', '', '', 1, 0, 'C', '0', '0', 'monitor:operlog:list', 'form', 'admin', '2025-10-13 15:33:36', '', null, '操作日志菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (501, '登录日志', 108, 2, 'logininfor', 'monitor/logininfor/index', '', '', 1, 0, 'C', '0', '0', 'monitor:logininfor:list', 'logininfor', 'admin', '2025-10-13 15:33:36', '', null, '登录日志菜单');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1000, '用户查询', 100, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:query', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1001, '用户新增', 100, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:add', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1002, '用户修改', 100, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:edit', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1003, '用户删除', 100, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:remove', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1004, '用户导出', 100, 5, '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:export', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1005, '用户导入', 100, 6, '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:import', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1006, '重置密码', 100, 7, '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:resetPwd', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1007, '角色查询', 101, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:query', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1008, '角色新增', 101, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:add', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1009, '角色修改', 101, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:edit', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1010, '角色删除', 101, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:remove', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1011, '角色导出', 101, 5, '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:export', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1012, '菜单查询', 102, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:query', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1013, '菜单新增', 102, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:add', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1014, '菜单修改', 102, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:edit', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1015, '菜单删除', 102, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:remove', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1016, '部门查询', 103, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:query', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1017, '部门新增', 103, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:add', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1018, '部门修改', 103, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:edit', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1019, '部门删除', 103, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:remove', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1020, '岗位查询', 104, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:query', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1021, '岗位新增', 104, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:add', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1022, '岗位修改', 104, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:edit', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1023, '岗位删除', 104, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:remove', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1024, '岗位导出', 104, 5, '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:export', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1025, '字典查询', 105, 1, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:query', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1026, '字典新增', 105, 2, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:add', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1027, '字典修改', 105, 3, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:edit', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1028, '字典删除', 105, 4, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:remove', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1029, '字典导出', 105, 5, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:export', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1030, '参数查询', 106, 1, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:query', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1031, '参数新增', 106, 2, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:add', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1032, '参数修改', 106, 3, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:edit', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1033, '参数删除', 106, 4, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:remove', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1034, '参数导出', 106, 5, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:export', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1035, '公告查询', 107, 1, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:notice:query', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1036, '公告新增', 107, 2, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:notice:add', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1037, '公告修改', 107, 3, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:notice:edit', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1038, '公告删除', 107, 4, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:notice:remove', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1039, '操作查询', 500, 1, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:query', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1040, '操作删除', 500, 2, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:remove', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1041, '日志导出', 500, 3, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:export', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1042, '登录查询', 501, 1, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:query', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1043, '登录删除', 501, 2, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:remove', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1044, '日志导出', 501, 3, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:export', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1045, '账户解锁', 501, 4, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:unlock', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1046, '在线查询', 109, 1, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:online:query', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1047, '批量强退', 109, 2, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:online:batchLogout', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1048, '单条强退', 109, 3, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:online:forceLogout', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1049, '任务查询', 110, 1, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:query', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1050, '任务新增', 110, 2, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:add', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1051, '任务修改', 110, 3, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:edit', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1052, '任务删除', 110, 4, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:remove', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1053, '状态修改', 110, 5, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:changeStatus', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1054, '任务导出', 110, 6, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:export', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1055, '生成查询', 116, 1, '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:query', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1056, '生成修改', 116, 2, '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:edit', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1057, '生成删除', 116, 3, '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:remove', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1058, '导入代码', 116, 4, '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:import', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1059, '预览代码', 116, 5, '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:preview', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (1060, '生成代码', 116, 6, '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:code', '#', 'admin', '2025-10-13 15:33:36', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2000, '图书商城', 0, 0, 'lib-mall', null, null, '', 1, 0, 'M', '0', '1', '', 'chart', 'admin', '2025-10-13 15:36:01', 'admin', '2025-11-03 15:57:37', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2001, '图书类别', 2000, 1, 'category', 'manage/category/index', null, '', 1, 0, 'C', '0', '0', '', 'tree-table', 'admin', '2025-10-13 19:17:32', 'admin', '2025-10-13 19:24:05', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2002, '图书审核', 2000, 2, 'book', 'manage/book/audit', null, '', 1, 0, 'C', '0', '0', '', 'swagger', 'admin', '2025-10-13 19:18:34', 'admin', '2025-10-13 19:19:07', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2003, '图书管理', 2000, 3, 'book', 'manage/book/index', null, '', 1, 0, 'C', '0', '0', null, 'skill', 'admin', '2025-10-13 19:20:06', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2004, '订单管理', 2000, 4, 'orders', 'manage/orders/index', null, '', 1, 0, 'C', '0', '0', null, 'cascader', 'admin', '2025-10-13 19:21:15', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2005, '图书列表', 2000, 5, 'book', 'manage/book/list', null, '', 1, 0, 'C', '0', '0', '', 'tab', 'admin', '2025-10-13 19:21:54', 'admin', '2025-10-13 19:22:13', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2006, '购物车管理', 2000, 6, 'carts', 'manage/carts/index', null, '', 1, 0, 'C', '0', '0', null, 'shopping', 'admin', '2025-10-13 19:22:50', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2007, '我的订单', 2000, 7, 'orders', 'manage/orders/manage', null, '', 1, 0, 'C', '0', '0', null, 'nested', 'admin', '2025-10-13 19:23:52', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2008, '用户管理', 2000, 7, 'user', 'manage/user/index', null, '', 1, 0, 'C', '0', '0', null, 'peoples', 'admin', '2025-10-13 19:30:09', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2009, '店铺管理', 2000, 8, 'shops', 'manage/shops/index', null, '', 1, 0, 'C', '0', '0', null, 'component', 'admin', '2025-10-13 20:11:38', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2010, '文件管理', 3, 4, 'upload', null, null, '', 1, 0, 'F', '0', '0', 'manage:upload:oss', 'download', 'admin', '2025-10-18 15:20:29', 'admin', '2025-10-18 15:21:20', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2011, '课程资源', 0, 0, '/manage/course-resource', '', null, '', 1, 0, 'M', '0', '0', '', 'date-range', 'admin', '2025-10-18 21:47:21', 'admin', '2025-10-19 12:00:32', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2012, '专业管理', 2011, 0, 'major', 'manage/courseResource/major/index', null, '', 1, 0, 'C', '0', '0', 'manage:major:list', '#', 'admin', '2025-10-18 21:48:50', 'admin', '2025-10-20 00:49:33', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2013, '新增', 2012, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:major:add', '#', 'admin', '2025-10-18 21:49:30', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2014, '修改', 2012, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:major:edit', '#', 'admin', '2025-10-18 21:49:54', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2015, '删除', 2012, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:major:remove', '#', 'admin', '2025-10-18 21:50:18', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2016, '查询', 2012, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:major:query', '#', 'admin', '2025-10-18 21:50:38', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2017, '课程管理', 2011, 1, 'course', 'manage/courseResource/course/index', null, '', 1, 0, 'C', '0', '0', 'manage:course:list', '#', 'admin', '2025-10-18 21:53:14', 'admin', '2025-10-20 00:55:05', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2018, '新增', 2017, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:course:add', '#', 'admin', '2025-10-18 21:53:37', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2019, '修改', 2017, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:course:edit', '#', 'admin', '2025-10-18 21:54:01', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2020, '删除', 2017, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:course:remove', '#', 'admin', '2025-10-18 21:54:19', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2021, '详情', 2017, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:course:query', '#', 'admin', '2025-10-18 21:54:43', 'admin', '2025-10-18 21:55:14', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2022, '专业负责人', 2011, 2, 'major-lead', 'manage/courseResource/majorLead/index', null, '', 1, 0, 'C', '0', '0', 'manage:majorLead:list', '#', 'admin', '2025-10-18 21:57:34', 'admin', '2025-10-20 00:55:11', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2023, '新增', 2022, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:majorLead:add', '#', 'admin', '2025-10-18 21:58:33', 'admin', '2025-10-18 21:59:02', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2024, '删除', 2022, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:majorLead:remove', '#', 'admin', '2025-10-18 21:58:52', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2025, '资源列表', 2011, 3, 'approved', 'manage/courseResource/approved', null, '', 1, 0, 'C', '0', '0', 'manage:courseResource:list', '#', 'admin', '2025-10-18 22:00:03', 'admin', '2025-10-20 00:55:18', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2026, '新增', 2025, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:add', '#', 'admin', '2025-10-18 22:00:48', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2027, '修改', 2025, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:edit', '#', 'admin', '2025-10-18 22:01:06', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2028, '强制删除', 2025, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:remove', '#', 'admin', '2025-10-18 22:01:28', 'admin', '2025-10-19 11:39:53', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2029, '详情', 2025, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:query', '#', 'admin', '2025-10-18 22:01:45', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2030, '审核通过', 2025, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:approve', '#', 'admin', '2025-10-18 22:02:06', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2031, '驳回', 2025, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:reject', '#', 'admin', '2025-10-18 22:02:22', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2032, '下架', 2025, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:offline', '#', 'admin', '2025-10-18 22:02:40', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2033, '上架', 2025, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:online', '#', 'admin', '2025-10-18 22:02:58', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2034, '下载', 2025, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:download', '#', 'admin', '2025-10-18 22:03:29', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2035, '待审核', 2011, 4, 'audit', 'manage/courseResource/audit', null, '', 1, 0, 'C', '0', '0', 'manage:courseResource:list', '#', 'admin', '2025-10-19 10:58:53', 'admin', '2025-10-20 00:55:24', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2036, '审核通过', 2035, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:approve', '#', 'admin', '2025-10-19 10:59:41', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2037, '审核驳回', 2035, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:reject', '#', 'admin', '2025-10-19 11:00:01', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2038, '详情', 2035, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:query', '#', 'admin', '2025-10-19 11:00:23', 'admin', '2025-10-19 11:37:46', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2039, '回收站', 2011, 5, 'trash', 'manage/courseResource/trash', null, '', 1, 0, 'C', '0', '0', 'manage:courseResource:list', '#', 'admin', '2025-10-19 11:38:29', 'admin', '2025-10-20 00:55:29', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2040, '重新上架', 2039, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:online', '#', 'admin', '2025-10-19 11:39:02', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2041, '强制删除', 2039, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:remove', '#', 'admin', '2025-10-19 11:39:29', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2042, '通知公告', 0, 3, '/manage/notice', null, null, '', 1, 0, 'M', '0', '0', '', 'message', 'admin', '2025-10-20 00:25:25', 'admin', '2025-11-08 11:16:19', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2062, '公告管理', 2042, 0, 'index', 'manage/notice/index', null, '', 1, 0, 'C', '0', '0', 'manage:notice:list', '#', 'admin', '2025-11-03 10:45:00', 'admin', '2025-11-03 11:12:47', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2063, '新增', 2062, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:notice:add', '#', 'admin', '2025-11-03 10:45:34', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2064, '修改', 2062, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:notice:edit', '#', 'admin', '2025-11-03 10:45:51', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2065, '删除', 2062, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:notice:remove', '#', 'admin', '2025-11-03 10:47:14', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2066, '发布/撤回', 2062, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:notice:publish', '#', 'admin', '2025-11-03 10:47:39', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2067, '置顶', 2062, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:notice:pin', '#', 'admin', '2025-11-03 10:47:59', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2068, '公告编辑', 2042, 0, 'edit', 'manage/notice/edit', null, '', 1, 0, 'C', '1', '0', 'manage:notice:edit', '#', 'admin', '2025-11-03 11:33:13', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2069, '下载', 2035, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:download', '#', 'admin', '2025-11-04 17:01:46', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2070, '下载', 2039, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:download', '#', 'admin', '2025-11-04 17:02:03', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2071, '最佳', 2025, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:courseResource:best', '#', 'admin', '2025-11-04 21:26:50', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2072, '数字图书馆', 0, 1, '/manage/library', null, null, '', 1, 0, 'M', '0', '0', '', 'education', 'admin', '2025-11-05 16:45:39', 'admin', '2025-11-08 11:15:51', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2073, '图书列表', 2072, 0, 'list', 'manage/library/ApprovedList', null, '', 1, 0, 'C', '0', '0', 'manage:library:list', '#', 'admin', '2025-11-05 16:48:15', 'admin', '2025-11-05 21:17:25', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2074, '待审核', 2072, 0, 'audit', 'manage/library/Audit', null, '', 1, 0, 'C', '0', '0', 'manage:library:list', '#', 'admin', '2025-11-05 16:48:44', 'admin', '2025-11-05 21:02:58', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2075, '图书管理员', 2072, 0, 'librarian', 'manage/library/Librarian', null, '', 1, 0, 'C', '0', '0', 'manage:libraryLibrarian:list', '#', 'admin', '2025-11-05 16:49:32', 'admin', '2025-11-05 21:03:12', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2076, '查看', 2073, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:library:get', '#', 'admin', '2025-11-05 16:49:57', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2077, '新增', 2073, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:library:add', '#', 'admin', '2025-11-05 16:50:14', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2078, '编辑', 2073, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:library:edit', '#', 'admin', '2025-11-05 16:50:30', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2079, '删除', 2073, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:library:remove', '#', 'admin', '2025-11-05 16:50:47', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2080, '审核通过', 2073, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:library:approve', '#', 'admin', '2025-11-05 16:51:07', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2081, '审核驳回', 2073, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:library:reject', '#', 'admin', '2025-11-05 16:51:33', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2082, '下架', 2073, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:library:offline', '#', 'admin', '2025-11-05 16:51:52', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2083, '上架待审', 2073, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:library:online', '#', 'admin', '2025-11-05 16:52:17', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2084, '硬删除', 2073, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:library:hardRemove', '#', 'admin', '2025-11-05 16:52:47', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2085, '任命', 2075, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:libraryLibrarian:add', '#', 'admin', '2025-11-05 16:53:51', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2086, '卸任', 2075, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:libraryLibrarian:remove', '#', 'admin', '2025-11-05 16:54:08', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2087, '回收站', 2072, 0, 'recycle', 'manage/library/Recycle', null, '', 1, 0, 'C', '0', '0', 'manage:book:list', '#', 'admin', '2025-11-05 21:49:26', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2088, '功能房预约', 0, 2, '/manage/facility', null, null, '', 1, 0, 'M', '0', '0', '', 'time', 'admin', '2025-11-06 14:41:56', 'admin', '2025-11-08 11:16:03', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2089, '楼房管理', 2088, 0, 'building', 'manage/facility/building/index', null, '', 1, 0, 'C', '0', '0', null, '#', 'admin', '2025-11-06 14:43:57', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2090, '列表', 2089, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:building:list', '#', 'admin', '2025-11-06 14:44:18', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2092, '查看', 2089, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:building:get', '#', 'admin', '2025-11-06 14:44:57', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2093, '新增', 2089, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:building:add', '#', 'admin', '2025-11-06 14:45:13', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2094, '修改', 2089, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:building:edit', '#', 'admin', '2025-11-06 14:45:32', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2095, '删除', 2089, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:building:remove', '#', 'admin', '2025-11-06 14:45:47', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2096, '房间管理', 2088, 0, 'room', 'manage/facility/room/index', null, '', 1, 0, 'C', '0', '0', '', '#', 'admin', '2025-11-06 14:46:07', 'admin', '2025-11-06 14:46:34', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2097, '列表', 2096, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:room:list', '#', 'admin', '2025-11-06 14:46:51', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2098, '查看', 2096, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:room:get', '#', 'admin', '2025-11-06 14:47:06', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2099, '时间轴', 2096, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:room:timeline', '#', 'admin', '2025-11-06 14:47:22', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2100, '新增', 2096, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:room:add', '#', 'admin', '2025-11-06 14:47:38', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2101, '修改', 2096, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:room:edit', '#', 'admin', '2025-11-06 14:47:53', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2102, '启用/禁用', 2096, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:room:enable', '#', 'admin', '2025-11-06 14:48:13', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2103, '删除', 2096, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:room:remove', '#', 'admin', '2025-11-06 14:48:30', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2104, '预约审核', 2088, 0, 'booking-audit', 'manage/facility/booking-audit/index', null, '', 1, 0, 'C', '0', '0', null, '#', 'admin', '2025-11-06 14:49:04', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2105, '审核列表', 2104, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:booking:audit:list', '#', 'admin', '2025-11-06 14:49:22', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2106, '审核通过', 2104, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:booking:audit:approve', '#', 'admin', '2025-11-06 14:49:38', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2107, '审核驳回', 2104, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:booking:audit:reject', '#', 'admin', '2025-11-06 14:49:53', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2108, '封禁管理', 2088, 0, 'ban', 'manage/facility/ban/index', null, '', 1, 0, 'C', '0', '0', null, '#', 'admin', '2025-11-06 14:50:46', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2109, '列表', 2108, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:ban:list', '#', 'admin', '2025-11-06 14:56:51', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2110, '封禁', 2108, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:ban:add', '#', 'admin', '2025-11-06 14:57:16', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2111, '解封', 2108, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:ban:remove', '#', 'admin', '2025-11-06 14:57:39', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2112, '审核设置', 2088, 0, 'setting', 'manage/facility/setting/index', null, '', 1, 0, 'C', '0', '0', null, '#', 'admin', '2025-11-06 15:00:34', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2113, '查看设置', 2112, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:setting:get', '#', 'admin', '2025-11-06 15:00:53', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2114, '修改设置', 2112, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:setting:edit', '#', 'admin', '2025-11-06 15:01:11', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2115, '排行榜', 2088, 0, 'top', 'manage/facility/top/index', null, '', 1, 0, 'C', '0', '0', '', '#', 'admin', '2025-11-06 15:02:04', 'admin', '2025-11-06 15:12:39', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2116, '房间榜', 2115, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:top:room', '#', 'admin', '2025-11-06 15:02:22', 'admin', '2025-11-06 15:12:48', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2117, '用户榜', 2115, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:top:user', '#', 'admin', '2025-11-06 15:02:37', 'admin', '2025-11-06 15:12:55', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2118, '失物招领', 0, 4, '/manage/lostfound', null, null, '', 1, 0, 'M', '0', '0', '', 'question', 'admin', '2025-11-07 09:52:25', 'admin', '2025-11-08 11:16:11', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2119, '已发布', 2118, 0, 'index', 'manage/lostfound/index', null, '', 1, 0, 'C', '0', '0', 'manage:lostfound:list', '#', 'admin', '2025-11-07 09:53:30', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2120, '待审核', 2118, 0, 'audit', 'manage/lostfound/audit', null, '', 1, 0, 'C', '0', '0', 'manage:lostfound:audit:list', '#', 'admin', '2025-11-07 09:54:21', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2121, '回收站', 2118, 0, 'recycle', 'manage/lostfound/recycle', null, '', 1, 0, 'C', '0', '0', 'manage:lostfound:recycle:list', '#', 'admin', '2025-11-07 09:55:00', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2122, '下架', 2119, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:lostfound:offline', '#', 'admin', '2025-11-07 09:55:24', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2123, '编辑', 2119, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:lostfound:edit', '#', 'admin', '2025-11-07 09:55:38', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2124, '通过', 2120, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:lostfound:audit:approve', '#', 'admin', '2025-11-07 09:55:59', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2125, '驳回', 2120, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:lostfound:audit:reject', '#', 'admin', '2025-11-07 09:56:17', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2126, '重新审核', 2121, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:lostfound:restore', '#', 'admin', '2025-11-07 09:56:42', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2127, '删除', 2121, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:lostfound:remove', '#', 'admin', '2025-11-07 09:56:57', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2129, '新增', 2118, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:lostfound:add', '#', 'admin', '2025-11-07 09:57:49', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2130, '详情', 2118, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:lostfound:get', '#', 'admin', '2025-11-07 09:58:18', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2131, '解决', 2119, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:lostfound:solve', '#', 'admin', '2025-11-07 10:09:25', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2132, '表单收集', 0, 5, '/manage/survey', null, null, '', 1, 0, 'M', '0', '0', '', 'checkbox', 'admin', '2025-11-07 21:54:54', 'admin', '2025-11-08 11:16:24', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2133, '问卷管理', 2132, 0, 'index', 'manage/survey/List', null, '', 1, 0, 'C', '0', '0', '', '#', 'admin', '2025-11-07 21:55:39', 'admin', '2025-11-07 22:08:04', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2134, '查看详情', 2133, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:survey:query', '#', 'admin', '2025-11-07 21:56:11', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2135, '新建', 2133, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:survey:add', '#', 'admin', '2025-11-07 21:56:31', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2136, '归档', 2133, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:survey:archive', '#', 'admin', '2025-11-07 21:56:48', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2137, '延期', 2133, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:survey:extend', '#', 'admin', '2025-11-07 21:57:11', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2138, '归档列表', 2132, 0, 'archive', 'manage/survey/List', null, '', 1, 0, 'C', '0', '0', 'manage:survey:list', '#', 'admin', '2025-11-07 22:02:52', 'admin', '2025-11-07 22:03:04', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2139, '新建表单', 2132, 0, 'new', 'manage/survey/Create', null, '', 1, 0, 'C', '0', '0', 'manage:survey:add', '#', 'admin', '2025-11-07 22:04:31', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2140, '置顶/取消', 2133, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:survey:pin', '#', 'admin', '2025-11-07 22:41:56', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2141, '发布草稿', 2133, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:survey:publish', '#', 'admin', '2025-11-07 23:59:30', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2142, '编辑草稿', 2133, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:survey:edit', '#', 'admin', '2025-11-08 00:00:02', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2143, '投票统计', 0, 6, '/manage/vote', null, null, '', 1, 0, 'M', '0', '0', '', 'chart', 'admin', '2025-11-08 09:22:07', 'admin', '2025-11-08 11:16:30', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2144, '投票列表', 2143, 0, 'index', 'manage/vote/List', null, '', 1, 0, 'C', '0', '0', 'manage:survey:list', '#', 'admin', '2025-11-08 09:23:07', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2145, '投票归档', 2143, 0, 'archive', 'manage/vote/List', null, '', 1, 0, 'C', '0', '0', 'manage:survey:list', '#', 'admin', '2025-11-08 09:23:51', 'admin', '2025-11-08 09:29:36', '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2146, '新建投票', 2143, 0, 'new', 'manage/vote/Create', null, '', 1, 0, 'C', '0', '0', 'manage:survey:add', '#', 'admin', '2025-11-08 09:24:40', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2147, '查看详情', 2144, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:survey:query', '#', 'admin', '2025-11-08 09:25:25', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2148, '新建', 2144, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:survey:add', '#', 'admin', '2025-11-08 09:25:46', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2149, '编辑', 2144, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:survey:edit', '#', 'admin', '2025-11-08 09:26:03', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2150, '发布', 2144, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:survey:publish', '#', 'admin', '2025-11-08 09:26:19', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2151, '延期', 2144, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:survey:extend', '#', 'admin', '2025-11-08 09:26:46', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2152, '归档', 2144, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:survey:archive', '#', 'admin', '2025-11-08 09:27:07', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2153, '置顶', 2144, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:survey:pin', '#', 'admin', '2025-11-08 09:27:28', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2154, '甘特图', 2089, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:facility:building:gantt', '#', 'admin', '2025-11-08 21:32:49', '', null, '');
INSERT INTO ruoyi.sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (2155, '总结', 2133, 0, '', null, null, '', 1, 0, 'F', '0', '0', 'manage:survey:summary', '#', 'admin', '2025-11-09 00:15:21', '', null, '');
