create table tb_course_resource_log
(
    id          bigint auto_increment comment '主键ID'
        primary key,
    resource_id bigint                  not null comment '资源ID',
    action      varchar(32)             not null comment 'CREATE/EDIT/APPROVE/REJECT/OFFLINE/ONLINE/DOWNLOAD/DELETE/HARD_DELETE',
    actor_id    bigint                  null comment '操作者ID',
    actor_name  varchar(64)             null comment '操作者名称',
    ip          varchar(64)             null comment 'IP地址',
    user_agent  varchar(255)            null comment 'User-Agent',
    detail      text                    null comment '详情（JSON文本）',
    result      varchar(16)             null comment 'SUCCESS/FAIL',
    create_by   varchar(64) default ''  not null comment '创建者',
    create_time datetime                null comment '创建时间',
    update_by   varchar(64) default ''  not null comment '更新者',
    update_time datetime                null comment '更新时间',
    del_flag    char        default '0' not null comment '删除标志（0存在 2删除）'
)
    comment '课程资源操作日志表（审计）' charset = utf8mb4;

create index idx_log_resource_time
    on tb_course_resource_log (resource_id, create_time);

INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (1, 10001, 'CREATE', 1, 'admin', '127.0.0.1', 'Mozilla/5.0', '{"note":"初始化导入示例"}', 'SUCCESS', 'admin', '2025-10-18 21:27:37', 'admin', '2025-10-18 21:27:37', '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (2, 10001, 'APPROVE', 1, 'admin', '127.0.0.1', 'Mozilla/5.0', '{"note":"审核通过"}', 'SUCCESS', 'admin', '2025-10-18 21:27:37', 'admin', '2025-10-18 21:27:37', '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (3, 10002, 'CREATE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-10-18 22:26:01', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (4, 10002, 'APPROVE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-10-18 22:28:34', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (5, 10002, 'DOWNLOAD', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-10-18 22:31:39', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (6, 10002, 'DOWNLOAD', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-10-18 22:31:50', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (7, 10002, 'DOWNLOAD', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-10-18 22:32:55', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (8, 10002, 'OFFLINE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-10-18 22:35:58', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (9, 10002, 'ONLINE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-10-18 22:37:09', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (10, 10002, 'REJECT', 1, 'admin', null, null, '外链不可达', 'SUCCESS', 'admin', '2025-10-18 22:39:39', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (11, 10002, 'DELETE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-10-18 22:42:36', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (12, 10001, 'OFFLINE', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-04 16:47:49', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (13, 10001, 'ONLINE', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-04 16:47:55', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (14, 10001, 'APPROVE', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-04 16:49:58', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (15, 10001, 'OFFLINE', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-04 17:03:02', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (16, 10001, 'ONLINE', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-04 17:03:25', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (17, 10003, 'CREATE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-04 17:22:59', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (18, 10001, 'REJECT', 1, 'admin', null, null, '无法下载', 'SUCCESS', 'admin', '2025-11-04 17:35:42', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (19, 10001, 'DELETE', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-04 17:35:59', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (20, 10003, 'APPROVE', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-04 17:36:12', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (21, 10003, 'DOWNLOAD', null, 'portal', null, null, null, 'SUCCESS', 'portal', '2025-11-04 20:18:32', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (22, 10003, 'BEST', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-04 21:28:13', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (23, 10003, 'UNBEST', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-04 21:28:16', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (24, 10003, 'BEST', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-04 21:28:58', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (25, 10003, 'DOWNLOAD', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-05 00:40:32', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (26, 10003, 'DOWNLOAD', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-05 00:42:00', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (27, 10003, 'DOWNLOAD', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-05 00:43:12', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (28, 10003, 'DOWNLOAD', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-05 00:52:24', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (29, 10003, 'DOWNLOAD', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-05 00:55:11', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (30, 10003, 'DOWNLOAD', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-05 00:55:19', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (31, 10005, 'CREATE', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-05 09:52:26', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (32, 10005, 'APPROVE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-05 09:57:44', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (33, 10005, 'BEST', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-05 09:57:54', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (34, 10005, 'UNBEST', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-05 09:57:56', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (35, 10005, 'BEST', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-05 09:57:59', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (36, 10003, 'UNBEST', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-05 09:58:01', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (37, 10005, 'OFFLINE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-06 09:21:26', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (38, 10005, 'ONLINE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-06 09:48:47', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (39, 10005, 'REJECT', 1, 'admin', null, null, '没有文件', 'SUCCESS', 'admin', '2025-11-06 09:49:03', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (40, 10005, 'ONLINE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-06 09:49:13', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (41, 10005, 'APPROVE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-06 09:49:17', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (42, 10003, 'OFFLINE', 1, 'admin', null, null, '文件不对', 'SUCCESS', 'admin', '2025-11-06 09:49:32', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (43, 10005, 'OFFLINE', 1, 'admin', null, null, '文件不对', 'SUCCESS', 'admin', '2025-11-06 09:50:37', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (44, 10005, 'ONLINE', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-06 09:55:45', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (45, 10005, 'REJECT', 1, 'admin', null, null, '请补全材料', 'SUCCESS', 'admin', '2025-11-06 09:56:28', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (46, 10005, 'ONLINE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-06 09:56:52', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (47, 10005, 'APPROVE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-06 09:56:56', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (48, 10005, 'OFFLINE', 1, 'admin', null, null, '已过时', 'SUCCESS', 'admin', '2025-11-06 09:57:22', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (49, 10005, 'ONLINE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-06 10:00:01', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (50, 10003, 'ONLINE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-06 10:00:23', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (51, 10005, 'EDIT', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-06 10:24:42', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (52, 10005, 'REJECT', 1, 'admin', null, null, '货不对版', 'SUCCESS', 'admin', '2025-11-06 10:25:10', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (53, 10005, 'EDIT', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-06 10:25:29', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (54, 10005, 'APPROVE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-06 10:26:40', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (55, 10005, 'OFFLINE', 1, 'admin', null, null, 'test', 'SUCCESS', 'admin', '2025-11-06 10:27:36', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (56, 10005, 'EDIT', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-06 10:28:01', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (57, 10007, 'CREATE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-07 17:11:11', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (58, 10008, 'CREATE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-07 17:15:26', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (59, 10008, 'APPROVE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-07 17:16:42', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (60, 10007, 'APPROVE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-07 17:17:18', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (61, 10007, 'EDIT', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-07 17:19:45', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (62, 10007, 'APPROVE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-07 17:20:40', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (63, 10007, 'OFFLINE', 1, 'admin', null, null, '', 'SUCCESS', 'admin', '2025-11-07 17:20:45', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (64, 10007, 'ONLINE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-07 17:21:56', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (65, 10005, 'APPROVE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-07 17:22:02', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (66, 10007, 'APPROVE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-07 17:22:03', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (67, 10003, 'APPROVE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-07 17:22:05', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (68, 10007, 'OFFLINE', 1, 'admin', null, null, '', 'SUCCESS', 'admin', '2025-11-07 17:22:13', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (69, 10005, 'OFFLINE', 1, 'admin', null, null, '', 'SUCCESS', 'admin', '2025-11-07 17:23:01', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (70, 10005, 'ONLINE', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-07 17:26:28', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (71, 10005, 'DELETE', 110, 'ogas', null, null, null, 'SUCCESS', 'ogas', '2025-11-07 17:29:24', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (72, 10010, 'CREATE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-08 15:22:07', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (73, 10011, 'CREATE', 114, 'demo', null, null, null, 'SUCCESS', 'demo', '2025-11-08 16:55:08', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (74, 10011, 'APPROVE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-08 16:55:31', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (75, 10012, 'CREATE', 115, '2023061001000318', null, null, null, 'SUCCESS', '2023061001000318', '2025-11-08 22:36:34', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (76, 10012, 'APPROVE', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-08 22:55:42', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (77, 10012, 'BEST', 1, 'admin', null, null, null, 'SUCCESS', 'admin', '2025-11-08 22:55:55', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (78, 10012, 'UNBEST', 111, 'test01', null, null, null, 'SUCCESS', 'test01', '2025-11-08 22:56:56', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (79, 10012, 'BEST', 111, 'test01', null, null, null, 'SUCCESS', 'test01', '2025-11-08 22:56:59', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (80, 10012, 'OFFLINE', 111, 'test01', null, null, 'ttttest', 'SUCCESS', 'test01', '2025-11-08 22:57:32', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (81, 10012, 'UNBEST', 111, 'test01', null, null, 'autoByOffline', 'SUCCESS', 'test01', '2025-11-08 22:57:32', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (82, 10012, 'ONLINE', 111, 'test01', null, null, null, 'SUCCESS', 'test01', '2025-11-08 22:57:42', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (83, 10012, 'APPROVE', 111, 'test01', null, null, null, 'SUCCESS', 'test01', '2025-11-08 22:57:46', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (84, 10012, 'BEST', 111, 'test01', null, null, null, 'SUCCESS', 'test01', '2025-11-08 22:57:58', '', null, '0');
INSERT INTO ruoyi.tb_course_resource_log (id, resource_id, action, actor_id, actor_name, ip, user_agent, detail, result, create_by, create_time, update_by, update_time, del_flag) VALUES (85, 10013, 'CREATE', 114, 'demo', null, null, null, 'SUCCESS', 'demo', '2025-11-09 09:41:16', '', null, '0');
